version: '3.8'

services:
  coqq:
    build:
      context: .
      dockerfile: Dockerfile
    image: coqq:latest
    container_name: coqq-dev
    volumes:
      # Mount source code for development
      - .:/home/opam/coqq
      # Persist opam cache
      - opam_cache:/home/opam/.opam
    working_dir: /home/opam/coqq
    # Keep container running for interactive development
    tty: true
    stdin_open: true
    # Override default command for development
    command: bash -c "eval $$(opam env) && bash"
    environment:
      - OPAM_SWITCH_PREFIX=/home/opam/.opam/default
      - CAML_LD_LIBRARY_PATH=/home/opam/.opam/default/lib/stublibs:/home/opam/.opam/default/lib/ocaml/stublibs:/home/opam/.opam/default/lib/ocaml
      - OCAML_TOPLEVEL_PATH=/home/opam/.opam/default/lib/toplevel
      - MANPATH=/home/opam/.opam/default/man:
      - PATH=/home/opam/.opam/default/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    user: opam

  # Service for building only (no interactive shell)
  coqq-build:
    build:
      context: .
      dockerfile: Dockerfile
    image: coqq:latest
    container_name: coqq-build
    volumes:
      - .:/home/opam/coqq
    working_dir: /home/opam/coqq
    command: bash -c "eval $$(opam env) && dune build"
    user: opam

volumes:
  opam_cache:
    driver: local